/*
 * enums.h
 *
 *  Created on: Oct 16, 2022
 *      Author: minht
 */

#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum
{
    APP_E_EVENT_NONE 						= 0x0000,
    APP_E_EVENT_BUTTON_UP,
    APP_E_EVENT_BUTTON_DOWN,
    APP_E_EVENT_BUTTON_ENTER,
    APP_E_EVENT_BUTTON_CANCEL,
    APP_E_EVENT_BUTTON_RESET,

	/* Network thread */
	APP_E_NETWORK_SEND_DATA 				= 0x0010,
	APP_E_NETWORK_SERVER_REV_DATA,
	APP_E_NETWORK_CLIENT_REV_DATA,
	APP_E_NETWORK_GET_TIME,

	/* SerialCOM thread */
	APP_E_SERIAL_CONFIG 					= 0x0020,
	APP_E_SERIAL_COM_1,
	APP_E_SERIAL_COM_2,
	APP_E_SERIAL_COM_3,
	APP_E_SERIAL_COM_4,
	APP_E_SERIAL_RS485,
	APP_E_SERIAL_SDI12,
	APP_E_SERIAL_SIM4G,

	/* Analog thread */
	APP_E_ANALOG_CHANNEL_1 					= 0x0030,
	APP_E_ANALOG_CHANNEL_2,
	APP_E_ANALOG_CHANNEL_3,
	APP_E_ANALOG_CHANNEL_4,
	APP_E_ANALOG_CHANNEL_5,
	APP_E_ANALOG_CHANNEL_6,
	APP_E_ANALOG_CHANNEL_7,
	APP_E_ANALOG_CHANNEL_8,
	APP_E_ANALOG_CHANNEL_9,
	APP_E_ANALOG_CHANNEL_10,
	APP_E_ANALOG_CHANNEL_11,
	APP_E_ANALOG_CHANNEL_12,

	/* Digital thread */
	APP_E_DIGITAL_CHANNEL_1 				= 0x0050,
	APP_E_DIGITAL_CHANNEL_2,
	APP_E_DIGITAL_CHANNEL_3,
	APP_E_DIGITAL_CHANNEL_4,
	APP_E_DIGITAL_CHANNEL_5,
	APP_E_DIGITAL_CHANNEL_6,
	APP_E_DIGITAL_READ_FREQUENCY
} APP_teEventType;

typedef enum
{
	N_ACTIVE       	= 0x00,
	ACTIVE		  	= 0x01
} Status_Logger;

typedef enum {
	E_SERIAL_CHANNEL_CONFIG = 0,
	E_SERIAL_CHANNEL_COM_1,
	E_SERIAL_CHANNEL_COM_2,
	E_SERIAL_CHANNEL_COM_3,
	E_SERIAL_CHANNEL_COM_4,
	E_SERIAL_CHANNEL_RS485,
	E_SERIAL_CHANNEL_SDI12,
	E_SERIAL_CHANNEL_SIM4G,
} APP_teSerialChannelId;

typedef enum {
	APP_E_UNIT_TEMPERATURE = 0,
	APP_E_UNIT_M,
	APP_E_UNIT_CO,
	APP_E_UNIT_PA,
	APP_E_UNIT_PPM,
	APP_E_UNIT_PPB
} APP_teUnits;

#endif /* ENUMS_H_ */
